# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a930298a98d4d28a5ea4fcbb04d20a57b33c7ea7371bb2d1b1e3f433676ab4bc7b2fb2db53999bc9d0bc7f0e0b46884eed8064026d0838077be4da8ec6b79212

test:
  secret_key_base: 1531cbfb8e66199e16d965d73cef2fbcfc22b0a80242d2ae873a427e5f15c208590082b283ce5207cf008408e885cf5234455ba3ff3b89a397d9f09fa0d105d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
